name: 'Setup PMD'
description: 'Setup PMD container'

runs:
  using: composite
  steps:
    - name: Pull PMD image
      shell: bash
      run: |
        podman pull docker.io/lobocode/pmd:7.10.0
        
        # Verify image
        if ! podman image exists docker.io/lobocode/pmd:7.10.0; then
            echo "Error: Failed to pull PMD image"
            exit 1
        fi
        
        # Create required directories
        mkdir -p .ast_cache test/src 