name: Upload Artifacts
runs:
  using: composite
  steps:
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rule-artifacts
        path: |
          rule.xml
          pmd_report.json
          .ast_cache/ 