name: 'Upload Artifacts'
description: 'Upload build artifacts'

runs:
  using: composite
  steps:
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rule-artifacts
        path: |
          rule.xml
          pmd_report.json
          .ast_cache/
        retention-days: 5
        compression-level: 6
        overwrite: true 