name: Rule Bridge CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Environment
      uses: ./.github/workflows/steps/setup-env
      
    - name: Setup PMD Container
      uses: ./.github/workflows/steps/setup-pmd
      
    - name: Configure Settings
      uses: ./.github/workflows/steps/configure
      
    - name: Run Tests
      uses: ./.github/workflows/steps/test
      
    - name: Upload Artifacts
      if: always()
      uses: ./.github/workflows/steps/artifacts 